# This workflow is triggered on push events to either 'main' or 'Develop' branches
on:
    push:
      branches:
      - main
      - Develop
  
  jobs:
    build_vue:
      name: deploy
      runs-on: ubuntu-latest
  
      steps:
        # Checks out the repository's code onto the runner
        - uses: actions/checkout@v2
  
        # Sets up Node.js environment and caches npm dependencies for faster builds.
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'  # Specifies the Node.js version
            cache: 'npm'       # Enables caching of npm dependencies
  
        # Installs project dependencies using npm
        - name: Install dependencies
          run: npm install
  
        # Optional: Lists the contents of the components directory for debugging purposes
        - name: List components directory
          run: ls -l src/components/
  
        # Builds the project by running the build script defined in package.json
        - name: Build Project
          run: npm run build
  
        # Deploys the build to the production S3 bucket if the push was to the 'main' branch
        - name: Deploy to S3
        # Conditional step based on the branch
          if: github.ref == 'refs/heads/main'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          run: |
            aws s3 sync dist/ s3://www.salvagg.io/ --exact-timestamps
            aws cloudfront create-invalidation --distribution-id EFJX169TXJMO5 --paths "/*"
  
        # Deploys the build to the test S3 bucket if the push was to the 'Develop' branch
        - name: Deploy to AWS S3 Test
        # Conditional step based on the branch
          if: github.ref == 'refs/heads/Develop'  
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          run: |
            aws s3 sync dist/ s3://test.salvagg.io/ --exact-timestamps
            aws cloudfront create-invalidation --distribution-id ENJW7KY6CVNEF --paths "/*"
  