name: Deploy to AWS S3
on: [ push ]

jobs:
  build_vue:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install dependencies and build your project
      - name: Build Project
        run: |
          npm install
          npm run build

      # Add any additional steps required for your deployment here
      # For example, setting up AWS credentials

      # Deploy to S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync dist/ s3://www.salvagg.io/
