# This workflow is triggered on push events to the 'main' branch.
on: 
  push:
    branches:
    - Develop
# Define the jobs in this workflow.
jobs:
  build_vue:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Optional step: List the contents of the components directory for debugging
      - name: List components directory
        run: ls -l src/components/

      # Step 4: Build the project
      - name: Build Project
        run: npm run build

      # Step 5: Deploy the built project to AWS S3 Bucket
      - name: Deploy to S3 Test
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        run: |
          aws s3 sync dist/ s3://test.salvagg.io/ --exact-timestamps
          aws cloudfront create-invalidation --distribution-id ENJW7KY6CVNEF --paths "/*"